allprojects {
    group = 'ru.ism'
    version = '1.0.0'
    repositories {
        mavenCentral() // Указываем репозиторий для зависимостей
    }
}

subprojects {
    apply plugin: 'java'
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
}