/*
 * Pay service
 * Pay service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.ism.mymarketapp.module.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.util.Objects;

/**
 * BalanceDto
 */
@JsonPropertyOrder({
  BalanceDto.JSON_PROPERTY_USER_ID,
  BalanceDto.JSON_PROPERTY_BALANCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class BalanceDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nonnull
  private Long userId;

  public static final String JSON_PROPERTY_BALANCE = "balance";
  @jakarta.annotation.Nonnull
  private Long balance;

  public BalanceDto() {
  }

  public BalanceDto userId(@jakarta.annotation.Nonnull Long userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Уникальный идентификатор пользователя
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Long userId) {
    this.userId = userId;
  }

  public BalanceDto balance(@jakarta.annotation.Nonnull Long balance) {
    
    this.balance = balance;
    return this;
  }

  /**
   * Остаток на балансе пользователя
   * @return balance
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BALANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBalance() {
    return balance;
  }


  @JsonProperty(value = JSON_PROPERTY_BALANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBalance(@jakarta.annotation.Nonnull Long balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BalanceDto balanceDto = (BalanceDto) o;
    return Objects.equals(this.userId, balanceDto.userId) &&
        Objects.equals(this.balance, balanceDto.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, balance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BalanceDto {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

