/*
 * Pay service
 * Pay service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.ism.mymarketapp.module.client;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.io.Serializable;
import java.util.Objects;

/**
 * BayDto
 */
@JsonPropertyOrder({
  BayDto.JSON_PROPERTY_USER_ID,
  BayDto.JSON_PROPERTY_BAY_SUM
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.19.0")
public class BayDto implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nonnull
  private Long userId;

  public static final String JSON_PROPERTY_BAY_SUM = "baySum";
  @jakarta.annotation.Nonnull
  private Long baySum;

  public BayDto() {
  }

  public BayDto userId(@jakarta.annotation.Nonnull Long userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Уникальный идентификатор пользователя
   * @return userId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getUserId() {
    return userId;
  }


  @JsonProperty(value = JSON_PROPERTY_USER_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUserId(@jakarta.annotation.Nonnull Long userId) {
    this.userId = userId;
  }

  public BayDto baySum(@jakarta.annotation.Nonnull Long baySum) {
    
    this.baySum = baySum;
    return this;
  }

  /**
   * Сумма покупки
   * @return baySum
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_BAY_SUM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBaySum() {
    return baySum;
  }


  @JsonProperty(value = JSON_PROPERTY_BAY_SUM, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBaySum(@jakarta.annotation.Nonnull Long baySum) {
    this.baySum = baySum;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BayDto bayDto = (BayDto) o;
    return Objects.equals(this.userId, bayDto.userId) &&
        Objects.equals(this.baySum, bayDto.baySum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, baySum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BayDto {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    baySum: ").append(toIndentedString(baySum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

