spring.application.name=my-market-app

spring.r2dbc.url=${DATASOURCE.URL:r2dbc:postgresql://localhost:6432/market}
spring.r2dbc.username=user
spring.r2dbc.password=user
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=50
spring.r2dbc.pool.max-idle-time=30s
spring.r2dbc.pool.max-life-time=10m
spring.r2dbc.pool.validation-query=SELECT 1

spring.sql.init.mode=always

